### ISSUE TITLE
Confusion Scroll - 'NoneType' iteration issue

### ISSUE THREAD

**Issue by NonMajorNerd** [observantdoggo/Arel#1]
The following traceback occurs when a target is selected after using a Confusion Scroll.

```
Traceback (most recent call last):
  File "C:\Users\od\Desktop\Projects\LCA\engine.py", line 420, in <module>
    main()
  File "C:\Users\od\Desktop\Projects\LCA\engine.py", line 414, in main
    play_game(player, entities, game_map, message_log, game_state, con, panel, constants)
  File "C:\Users\od\Desktop\Projects\LCA\engine.py", line 328, in play_game
    for enemy_turn_result in enemy_turn_results:
TypeError: 'NoneType' object is not iterable
```

**Comment by NonMajorNerd** [comment]
This has been solved by checking that the enemy_turn_results list is populated prior to attempting to iterate through the list.

```for enemy_turn_result in enemy_turn_results:```

in the engine (approx. line 328) was updated to read
```
if enemy_turn_results != None:
     for enemy_turn_result in enemy_turn_results:
```
